# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7b2a2390305d96f66ec4354c5e78ea0c52cb1348878060088f9b4d636f995d811dd851c3a0d517a1011208d5d263f1845e0105274e24669400c2c56170463de

test:
  secret_key_base: 9a28774ff15ffd9eabd9eb46bff5f6447fe9a12b64af419322583f859e85f7afc96248c01ea36533772ff0bb163bd00004c72c6d3556376a0e0753910ef39c25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
